#Tell Gitlab to load these environental vars from the variables list
variables:
  PYPI_USER: SECURE
  PYPI_PASS: SECURE

stages:
  - deploy

deploy docs to production:
  stage: deploy
  script:
    # Note: the group/username directory must already exist on the server before calling this command
    - rsync -avz -e'ssh -v' --numeric-ids --delete doc/build/html/* production_docs_rsync:WEISS/SoftwareRepositories/scikit-surgeryimage 2>&1
  tags:
    - docs-production
  environment:
    name: production
  only:
    - public
  dependencies:
    - build docs
    
    
deploy pip to production:

  stage: deploy
  when: manual
  only:
    - tags
    
  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/scikit-surgeryimage
    
  tags:
    - pip-production
    
  artifacts:
    paths:
    - dist/
    
  script:
    # Install packages required to build/publish
    # remove any previous distribution files
    - echo $PYPI_USER
    - pip install wheel twine setuptools
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # Upload to testpypi server
    - twine upload --repository pypi dist/* --username $PYPI_USER --password $PYPI_PASS --verbose

