#Tell Gitlab to load these environental vars from the variables list
variables:
  PYPI_USER: SECURE
  PYPI_PASS: SECURE

stages:
  - build
  - installer
  - test
  - deploy

.build-install-template: &build-install-template
  stage: build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]build?\]/i
  script:
    - tox -e installer
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

build docs:
  stage: build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]build?\]/i
  script:
    - tox -e docs
  tags:
    - shared-linux, gui
  artifacts:
    paths:
      - doc/
    expire_in: 1 week

build linux installer:
  <<: *build-install-template
  tags:
    - shared-linux, gui

build mac installer:
  <<: *build-install-template
  tags:
    - shared-mac, gui

build windows installer:
  <<: *build-install-template
  tags:
    - shared-win, gui

test Linux:
  stage: test
#  variables:
#    LD_LIBRARY_PATH: ${CI_PROJECT_DIR}/.tox/py36/lib/python3.6/site-packages/PySide2/Qt/plugins/platforms
#    DISPLAY: localhost:1
   script:
#    - echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
#    - echo "DISPLAY=${DISPLAY}"
    - tox
  tags:
    - shared-linux, gui
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

test macOS:
  stage: test
  script:
    - tox
  tags:
    - shared-mac, gui

test Windows:
  stage: test
  script:
    - tox
  tags:
    - shared-win, gui


deploy pip to production:
  stage: deploy
  when: manual
  only:
    - tags

  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/scikit-surgeryimage

  tags:
    - pip-production

  artifacts:
    paths:
      - dist/

  script:
    # Install packages required to build/publish
    # remove any previous distribution files
    - pip install wheel setuptools twine
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # Upload to testpypi server
    - twine upload --repository pypi dist/* --username $PYPI_USER --password $PYPI_PASS
