on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Set environmental variables for linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo "::set-env name=LD_LIBRARY_PATH::${{ github.workspace }}/.tox/py36/lib/python3.6/site-packages/PySide2/Qt/plugins/platforms"
          echo "::set-env name=DISPLAY::localhost:1"

      - name: Run tox
        run: |
          tox

  deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: python -m pip install wheel twine setuptools

      - name: Build wheel
        run: |
          python setup.py sdist

      - name: Publish package if tagged release
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
